# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20170523_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='finishedAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='list',
            name='todoAmount',
            field=models.IntegerField(default=0),
        ),
    ]
