# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dueDate',
            field=models.DateTimeField(),
        ),
    ]
