# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20170525_0634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='dueDate',
            new_name='due_Date',
        ),
    ]
